version: 2
jobs:
  build:
    working_directory: /tmp/build
    docker:
      - image: tegud/circleci-nodejs-docker
    steps:
      - checkout

      - setup_remote_docker

      # build and push Docker image
      - run: |
          npm i
          TAG=$CIRCLE_BUILD_NUM
          docker build -t tegud/tegud-blog:v1 .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push tegud/tegud-blog:v1
